2023総会を追加
sphinxjp/sphinx-users.jp pull request #108
Opened 2023-10-21 09:11 UTC by shimizukawa

総会の案内を出します。

## タイムライン

* 2023/11/12（日） ～ 2022/11/25（土）役員推薦
* 2023/11/26（日） ～ 2022/12/07（木）役員の選出投票、決算承認可否の投票
* 2023/12/08（金） 20:00～22:00 総会: 役員の採択、決算の承認を実施

## 3役推薦フォームの案内文

slack のgeneralで配信
```
@channel sphinx-users.jp ユーザー会の2024年度の役員（会長1名、副会長2名、会計1名）を募集します。自薦他薦は問いません。このSlackの人はだれでも応募可能です。

推薦された方を次のフォームにて選出投票し、これを元に 2023年度総会にて採決、承認を行います（立候補制ではないため、投票を考慮のうえ、本人による承諾のうえ決定します）。

参考: 2023年度の役員

- 会長: @tkoyama010 （小山）
- 副会長: @usaturn （山田）
- 副会長: @JunyaFff （福田）
- 会計: @shimizukawa （清水川）

本フォームでは、役員の推薦を1人1回行えます.
よろしくおねがいします。
<FORM URL TBD>
```

フォーム編集URL <URL TBD>

## 役員選出投票、会計承認の案内文

slackのgeneralで配信
```
@channel sphinx-users.jp ユーザー会の2023年度の役員改選投票、会計報告の承認フォームです。
<FORM URL TBD>

12/08金 20:00~22:00 で実施する「2023年度総会」にて採決、承認を行います（立候補制ではないため、投票を考慮のうえ、本人による承諾のうえ決定します）。
本フォームでは投票を1人1回行えます.
投票期間は11/26~12/07 24:00まで
よろしくおねがいします
```
フォーム編集URL <FORM URL TBD>

2023-10-21 09:17 UTC, tkoyama010 requested changes

2023-10-21 09:17 UTC, tkoyama010 commented on source/event/20231208_general_meeting/index.rst
> +.. @shimizukawa: （副会長）
コメント部分ですが、下の役員の改選の情報に合わせました。
```suggestion
.. @tkoyama010: （会長挨拶）
..
.. @usaturn: （副会長）
..
.. @JunyaFff: （副会長）
..
.. @shimizukawa: （会計）

```

2023-10-21 09:17 UTC, tkoyama010 commented on source/event/20231208_general_meeting/index.rst
> +..   :会計: @shimizukawa
すごい結果だ。

2023-10-21 09:18 UTC, tkoyama010 approved these changes
LGTM

2023-11-12 04:42 UTC, shimizukawa commented
11月の経費を追加してマージします

2023-11-12 05:01 UTC, merged