:wastebasket: sphinx-users-jp メーリングリストの廃止
sphinxjp/sphinx-users.jp pull request #41
Opened 2019-12-08 08:01 UTC by tkoyama010

ユーザー会参加条件にある「メーリングリスト」を廃止する
第６条 （入 会）
第７条 （退 会）
第８条 （除 名）

2019-12-08 08:05 UTC, tk0miya commented on source/regulations.rst
>  2. 個人会員が死亡したとき。
こんな条項あったんだ… 😇

2019-12-08 08:06 UTC, tk0miya requested changes

2019-12-08 08:06 UTC, tk0miya commented on source/regulations.rst
>  なおメーリングリスト、チャットへの参加は自由に行うことが出来る。
メーリングリストが残ってました！

2019-12-08 08:07 UTC, tkoyama010 commented on source/regulations.rst
>  なおメーリングリスト、チャットへの参加は自由に行うことが出来る。
ありがとうございます。修正しました。

2019-12-08 08:08 UTC, tkoyama010 commented on source/regulations.rst
>  2. 個人会員が死亡したとき。
チャットから脱退しただけでアウト。死亡したらアウト。

2019-12-08 08:13 UTC, tkoyama010 commented
とりあえず👆忘れないうちにマージしておきます。何か気がついたら再度PR or コミットしてください👍

2019-12-08 08:13 UTC, merged

2019-12-08 08:17 UTC, tk0miya commented
ぐっじょぶ！

2019-12-10 03:02 UTC, shimizukawa commented
ぐっじょーーーーぶ！（忘れてた