`add_stylesheet` 廃止にともなうNoteの追加
sphinxjp/sphinx-users.jp pull request #89
Opened 2021-05-10 02:31 UTC by terapyon

`add_stylesheet` 廃止にともなうNoteの追加

2021-05-10 02:45 UTC, tkoyama010 requested changes
@terapyon ありがとうございます。`setup` 自体を書き換えてしまってはいかがでしょうか？

2021-05-10 02:45 UTC, tkoyama010 commented on source/reverse-dict/html/custom-css-js.rst
> +
```suggestion
          app.add_css_file('custom.css')

```

2021-05-10 03:33 UTC, terapyon commented on source/reverse-dict/html/custom-css-js.rst
> +
運用方針やこのコンテンツの更新方針がわからないので、Noteで追加しました。
以前にここを見たひとが、メソッド名だけが直っていると、変化に気が付かないかなって思ってNoteでは残しておきたいなと思いました。

2021-05-10 03:39 UTC, tkoyama010 commented on source/reverse-dict/html/custom-css-js.rst
> +
ご意見ありがとうございます。
> 以前にここを見たひとが、メソッド名だけが直っていると、変化に気が付かないかなって思ってNoteでは残しておきたいなと思いました。

確かにそうですね。それではsetupを修正してかつNoteも追加するということでいかがでしょう？
```suggestion
          app.add_css_file('custom.css')

.. note::

   ``add_stylesheet`` メソッドは、Sphinx 4.0で廃止されたため ``add_css_file`` メソッドに修正しました( `#89 <https://github.com/sphinxjp/sphinx-users.jp/pull/89/>`_ )。
   https://www.sphinx-doc.org/ja/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file

```

2021-05-10 03:46 UTC, tk0miya commented
`add_stylesheet()` から `add_css_file()` へのリネームは 1.8 で行われたようですね。
https://www.sphinx-doc.org/ja/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file

1.8.0 のリリースが 2018.9 なのでもう 2年半経過したところですね。
Ubuntu LTS (18.04) で配布されているのは 1.6.7 なので、ここらへんに配慮すべきかどうかですかねー。
https://packages.ubuntu.com/bionic/python3-sphinx

開発者としては前に進んでほしいので言及しなくて良い (バージョン上げてほしい)ところですが、ユーザー会としては門戸を狭めない方がよいのでは、と考えます。
ということで、note で書く案に +0.5 票を投じます。

いずれにしても`add_stylesheet()` には未来がない (もう削除された) ので、本文で紹介するのは `add_css_file()` がよいですね。

2021-05-10 03:47 UTC, tk0miya commented
コメントしたあとに気づきましたが、 `html_css_files` って設定項目が 1.8 から存在するんですよね。
わざわざ `setup()` を書く必要もないのでこちらを紹介した方がよさそうです…。
https://www.sphinx-doc.org/ja/master/usage/configuration.html#confval-html_css_files

2021-05-10 03:48 UTC, tk0miya commented
sphinx-users.jp のサイト自体が `add_stylesheet()` を使っているのでビルドできないワロタ…

2021-05-11 06:31 UTC, terapyon commented
ユーザかとして、また、お勧めの書き方を知らないので、私はこの提案までで手を引きたいと思いますがいかがでしょうか？
適切な表現が公開されることを望んでいます。

2021-05-11 06:55 UTC, tkoyama010 commented on source/reverse-dict/html/custom-css-js.rst
>            app.add_stylesheet('custom.css')
```suggestion
      html_css_files = ['custom.css']
```

2021-05-11 06:57 UTC, tkoyama010 commented on source/reverse-dict/html/custom-css-js.rst
> +   https://www.sphinx-doc.org/ja/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file
```suggestion
   この ``add_stylesheet`` メソッドは、Sphinx 4.0で廃止されました。代わりに、 ``html_css_files`` リストを使います。
   https://www.sphinx-doc.org/ja/master/usage/configuration.html#confval-html_css_files
```

2021-05-11 07:00 UTC, tkoyama010 commented
@terapyon  ご協力ありがとうございました。
@tk0miya  `html_css_files` を使用する表現に更新しました。レビューをお願いできますか？

2021-05-11 13:46 UTC, tk0miya commented on source/reverse-dict/html/custom-css-js.rst
> +   この ``add_stylesheet`` メソッドは、Sphinx 4.0で廃止されました。代わりに、 ``html_css_files`` リストを使います。
例が入れ替わってしまったので「この add_stylesheet」が指すものがなくなってしまいました。
このくらいで良さそうです。
```suggestion
   Sphinx-1.8 以前は ``setup()`` 関数を定義し、その中で ``add_stylesheet()`` を呼び出していましたが、
   現在では設定項目 ``html_css_files`` を使って設定します。
```

2021-05-11 13:47 UTC, tk0miya commented
一箇所コメントしました。あとはよさそうです
(Slack 通知がコケてますが、問題ないのでマージしちゃって良さそうです)

2021-05-11 21:35 UTC, tkoyama010 commented
ありがとうございます。

2021-05-11 21:36 UTC, merged