sphinx-users.jp 2021 総会案内
sphinxjp/sphinx-users.jp pull request #92
Opened 2021-12-19 07:39 UTC by shimizukawa

総会の案内を出します。

2021-12-19 08:01 UTC, shimizukawa commented
副会長の @usaturn @tkoyama010 2名でレビューをお願いします。

2021-12-19 08:09 UTC, tkoyama010 requested changes

2021-12-19 08:09 UTC, tkoyama010 commented on source/event/20220129_general_meeting/index.rst
> +* 2021年度: 会長 @shimizukawa（清水川）, 副会長 @usaturn（山田）, 副会長 @tkoyama010（小山）, 会計 @shimizukawa（清水川）
@tkoyama010 が会長だったと記憶してます。前年度の記録が多分間違ってます。

2021-12-19 08:45 UTC, usaturn requested changes

2021-12-19 08:45 UTC, usaturn commented on source/event/20220129_general_meeting/index.rst
> +:場所: Meet
```suggestion
:場所: Google Meet
```

2021-12-19 08:45 UTC, usaturn commented on source/event/20220129_general_meeting/index.rst
> +========================================
現状で warning 出ちゃうけど、いいの？

2021-12-19 08:45 UTC, usaturn commented on source/event/20220129_general_meeting/index.rst
> +今回は、薬礼の変更はありません。
```suggestion
今回は、約例の変更はありません。
```

2021-12-19 08:54 UTC, tk0miya commented on source/event/20220129_general_meeting/index.rst
> +========================================
```suggestion
===========================================
sphinx-users.jp 2021年総会(2022/01/29 or 30)
===========================================
```

2021-12-20 19:17 UTC, shimizukawa commented on source/event/20220129_general_meeting/index.rst
> +* 2021年度: 会長 @shimizukawa（清水川）, 副会長 @usaturn（山田）, 副会長 @tkoyama010（小山）, 会計 @shimizukawa（清水川）
なんだってー！

2021-12-20 19:22 UTC, shimizukawa commented
イベントの日が決まってからマージしてアナウンスすればええやん、ということに気づいてしまった

2021-12-20 19:24 UTC, shimizukawa commented on source/event/20220129_general_meeting/index.rst
> +* 2021年度: 会長 @shimizukawa（清水川）, 副会長 @usaturn（山田）, 副会長 @tkoyama010（小山）, 会計 @shimizukawa（清水川）
ほんとうだ・・
![image](https://user-images.githubusercontent.com/151623/146821413-b913a173-e10b-4a6a-8e87-647315ac7a93.png)

2021-12-20 19:33 UTC, shimizukawa commented
@usaturn @tkoyama010 再確認お願いします！

2021-12-20 19:37 UTC, shimizukawa commented on source/event/20220129_general_meeting/index.rst
> +sphinx-users.jp 2021年総会(2022/01/29 or 30)
メモ: 29 or 30 が確定したらマージします。

2021-12-20 19:38 UTC, shimizukawa commented on source/event/20220129_general_meeting/index.rst
> +:日時: 2022/01/29(土) or 30(日) 13:00~14:00
TODO: ここも要確定

2021-12-21 00:54 UTC, tkoyama010 approved these changes
LGTM

2022-01-04 08:28 UTC, shimizukawa commented
1/29で確定させます

2022-01-04 08:42 UTC, shimizukawa commented
Connpass公開した
https://sphinxjp.connpass.com/event/234494/

2022-01-04 08:42 UTC, merged

2022-01-04 08:43 UTC, shimizukawa commented
マージした